platform :ios, '16.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'NAOHealthSync' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,  # or false if not using Hermes
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # --- REMOVE OR COMMENT OUT THE TESTS TARGET ---
  # target 'NAOHealthSyncTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  post_install do |installer|
    react_native_post_install(installer)
  end
end